version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6-buster
    working_directory: /home/circleci/tskit
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci *
      - restore_cache:
          # It's sometimes necessary to nuke the cache, and the simplest
          # way to do it is to change the key. We can increment this
          # version number when we want to do this.
          key: tskit-{{ .Branch }}-v1
      - run:
          name: Checkout submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Install dependencies and set path
          command: |
            sudo apt-get install ninja-build libcunit1-dev valgrind clang doxygen \
            libgsl-dev
            # Install meson to the system packages so we can run it as root
            sudo pip install meson==0.55
            pip install --user -r python/requirements/CI-complete/requirements.txt
            pip install twine --user
            # Remove tskit installed by msprime
            pip uninstall tskit -y
            echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
      - save_cache:
          key: tskit-{{ .Branch }}-v1
          paths:
            - "/home/circleci/.local"

      - run:
          name: Compile Python
          command: |
            cd python && make allchecks

      - run:
          name: Compile C with gcc
          command: |
            meson build-gcc c -D b_coverage=true
            ninja -C build-gcc

      - run:
          name: Compile C with clang
          command: |
            CC=clang CXX=clang++ meson build-clang c
            ninja -C build-clang

      - run:
          name: Run C tests
          command: |
            ninja -C build-gcc test

      - run:
          name: Run gcov & upload coverage.
          command: |
            cd build-gcc
            # TODO should be able to do this with 'find', but it's tricky and opaque.
            gcov -pb libtskit.a.p/tskit_core.c.gcno ../c/tskit/core.c
            gcov -pb libtskit.a.p/tskit_tables.c.gcno ../c/tskit/tables.c
            gcov -pb libtskit.a.p/tskit_trees.c.gcno ../c/tskit/trees.c
            gcov -pb libtskit.a.p/tskit_genotypes.c.gcno ../c/tskit/genotypes.c
            gcov -pb libtskit.a.p/tskit_core.c.gcno ../c/tskit/core.c
            gcov -pb libtskit.a.p/tskit_convert.c.gcno ../c/tskit/convert.c
            gcov -pb libtskit.a.p/tskit_stats.c.gcno ../c/tskit/stats.c
            gcov -pb libtskit.a.p/tskit_haplotype_matching.c.gcno ../c/tskit/haplotype_matching.c
            gcov -pb libtskit.a.p/tskit_file_format.c.gcno ../c/tskit/file_format.c
            cd ..
            bash <(curl -s https://codecov.io/bash) -X gcov -n c_tests

      - run:
          name: Valgrind for C tests.
          command: |
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/test_core
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/test_tables
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/test_trees
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/test_genotypes
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/test_convert
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/test_stats
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/test_haplotype_matching
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/test_file_format
            valgrind --leak-check=full --error-exitcode=1 ./build-gcc/test_minimal_cpp

      - run:
          name: Run clang-compiled C tests
          command: |
            ninja -C build-clang test

      - run:
          name: Test building with meson subproject
          command: |
            meson build-subproject c/tests/meson-subproject
            ninja -C build-subproject
            ./build-subproject/example

      - run:
          name: Install shared library and hand-compile program.
          command: |
            meson build-install c --prefix=/usr
            sudo ninja -C build-install install
            clang c/examples/api_structure.c -I c/subprojects/kastore -o api_structure -ltskit
            ./api_structure

      - run:
          name: Run example make file
          command: |
            make -C c/examples

      - run:
          name: Run Python tests
          command: |
            cd python
            python -m pytest --cov=tskit  --cov-report=xml --cov-branch -n8 tests

      - run:
          name: Upload Python coverage
          command: |
            # Make sure the C coverage reports aren't lying around
            rm -fR build-gcc
            bash <(curl -s https://codecov.io/bash) -X gcov -n python_tests
            # Clean up reports so we don't upload them twice.
            rm -f coverage.xml

            # Upload coverage for the Python C API.
            cd python
            gcov -pb -o ./build/temp.linux*/*.gcno _tskitmodule.c
            cd ..
            bash <(curl -s https://codecov.io/bash) -X gcov -n python_c_tests
            # Clean up reports so we don't upload them twice.
            rm -f python/*.gcov

      - run:
          name: Build Python package
          command: |
            cd python
            rm -fR build
            python setup.py sdist
            python setup.py check
            python -m twine check dist/*.tar.gz
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade setuptools pip wheel
            python setup.py build_ext
            python setup.py egg_info
            python setup.py bdist_wheel
            pip install dist/*.tar.gz
            tskit --help

      - run:
          name: Build example LWT interface code and test
          command: |
            # We're assuming that the tskit C module has already
            # been built, as we're testing against the local tskit version.
            cd python/lwt_interface
            make allchecks
            python -m pytest
